# fly.toml app configuration file generated for glyphdlp on 2023-10-09T11:35:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "glyphdlp"
primary_region = "den"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 2000
    hard_limit = 2200